name: default
channels:
    - conda-forge
dependencies:
    - python=3.7
    - pip
    - numpy
    - scipy
    - jupyter
    - jupyterlab
    - ipython
    - nb_conda
    - matplotlib
    - xarray
    - netcdf4
    - cartopy
    - pyjokes
    - fftw
    - gdal
    - ghostscript
    - libnetcdf
    - hdf5
    - zlib
    - curl
    - pcre
    - sphinx
